### PR TITLE
Fix isMouseEvent returning false for simulated context menu events

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
## Motivation
`isMouseEvent` was incorrectly returning `false` for events created via `Simulate.contextMenu`.

It looks like we were missing type-checking test coverage for contextmenu events (I checked to see if any more were missing, but contextmenu was the only one).

## Solution
- Update `type` string checks in `isMouseEvent` so that it returns `true` for simulated context menu events
- Update test coverage

## QA Instructions
- CI passes

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>Error scanning for security relevant changes</summary>
</details>
<details>
<summary>Error scanning for potential secrets</summary>
</details>
<details>
<summary>Error scanning for cfn validation issues</summary>
</details>

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 8f589bab1628899503b05f221ab1439d446a2e4b

Showing results for 8f589bab1628899503b05f221ab1439d446a2e4b
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/react-dart/8f589bab1628899503b05f221ab1439d446a2e4b).

**Review by joebingham-wk — APPROVED** [review]
Looks great! Thanks for fixing this, Greg! I can upgrade to a plus ten once CI passes

**Review by joebingham-wk — COMMENTED** [review]
QA +1
- [x] CI passing (dev run is expected to fail)

**Comment by aaronlademann-wf** [comment]
@aviary-wf try again please

**Comment by greglittlefield-wf** [comment]
@aviary-wf

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
