### PR TITLE
Replace mockito with mocktail

### PR DESCRIPTION
**Pull request by sourcegraph-wk**
In order to help with build times and ease null safety migration, we've opted to replace mockito with mocktail. This batch runs the codemod to swap things out, but may require manual intervention.
FEDX will come around and fix things up unless you beat us to it. Once CI is green and the PR is not in draft, you can review and merge it.
For more info, reach out to `#support-frontend-dx` on Slack.

[_Created by Sourcegraph batch change `Workiva/mocktail`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/mocktail)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]
+10 tests pass with mocktail instead of mockito

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
