### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by umeklinks**
Removed the word **where** on line 43, and **into** on line 45 from the sentence to clarify things.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>(2) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>elliptic < 6.5.4</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>ssri < 8.0.1</code> via <code>yarn.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=react-dart">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by aaronlademann-wf — APPROVED** [review]
+1

@Workiva/release-management-pp

**Comment by martinolson-wk** [comment]
RM +1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
