### PR TITLE
Fix bad aviary.yaml syntax

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
There was a hyphen before a comment that shouldn't have been there, causing Aviary to error

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>Error scanning for security relevant changes</summary>
</details>
<details>
<summary>Error scanning for potential secrets</summary>
</details>
<details>
<summary>Error scanning for cfn validation issues</summary>
</details>

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 1ad16a75629dd0223cd281e89cb442f355303777

Showing results for 1ad16a75629dd0223cd281e89cb442f355303777
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/react-dart/1ad16a75629dd0223cd281e89cb442f355303777).

**Review by jeffreymelvin-wf — APPROVED** [review]
+1 security

**Comment by jeffreymelvin-wf** [comment]
aviary override required

**Comment by jeffreymelvin-wf** [comment]
+1 security

**Review by aaronlademann-wf — APPROVED** [review]
+1

**Pull request merged**
