### PR TITLE
RM-139349 Release react-dart 6.1.7

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Bump minimist from 1.2.5 to 1.2.6](https://github.com/Workiva/react-dart/pull/335)
	* [Bump ansi-regex from 4.1.0 to 4.1.1](https://github.com/Workiva/react-dart/pull/338)
	* [Replace deprecated commands with new dart commands](https://github.com/Workiva/react-dart/pull/340)
	* [FW-151 Add skynet config that verifies that github workflow is successful](https://github.com/Workiva/react-dart/pull/341)
	* [Narrow dependency_validator range to avoid NNBD issue](https://github.com/Workiva/react-dart/pull/342)

Requested by: @greglittlefield-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/6.1.6...Workiva:release_react-dart_6.1.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/6.1.6...6.1.7

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4743698779471872/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4743698779471872/?repo_name=Workiva%2Freact-dart&pull_number=345)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>ansi-regex < 4.1.1</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>glob-parent < 5.1.2</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>terser < 4.8.1</code> via <code>yarn.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=react-dart">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by greglittlefield-wf — APPROVED** [review]
+10

**Review by sydneyjodon-wk — APPROVED** [review]

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
