### PR TITLE
[6.0.0] Resolve peerDependencies warning for react-redux

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
Self-explanatory.

However, given the amount of diff this generated in the JS source, I figured I'd put it up for a review.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(2) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>ini < 1.3.6</code> via <code>package-lock.json</code></li>
<li>1 vulns in <code>node-fetch < 2.6.1</code> via <code>package-lock.json</code></li>
</details>
<details>
<summary>Error scanning for security relevant changes</summary>
</details>
<details>
<summary>Error scanning for potential secrets</summary>
</details>
<details>
<summary>Error scanning for cfn validation issues</summary>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=react-dart">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 01aff355da2b00cd82e9d09f267e0b12c4376f14

Showing results for 01aff355da2b00cd82e9d09f267e0b12c4376f14
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/react-dart/01aff355da2b00cd82e9d09f267e0b12c4376f14).

**Comment by aaronlademann-wf** [comment]
@aviary-wf try again please

**Review by greglittlefield-wf — APPROVED** [review]
+10

**Pull request merged**
