### PR TITLE
Add `baseURI` polyfill for IE 11 compatibility on Dart 2.13

### PR DESCRIPTION
**Pull request by sydneyjodon-wk**
Added [this polyfill](https://github.com/webcomponents/webcomponents-platform/issues/2) to `react.js` to fix failing web_skin_dart IE 11 functional tests.

### QA Instructions

- [ ] CI passes (besides build - beta which fails on master)
- [ ] [WSD functional tests ](https://wf-skynet-hrd.appspot.com/apps/test/smithy/3028240/2)pass for Dart 2.13

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(6) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>browserslist < 4.16.5</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>elliptic < 6.5.4</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>glob-parent < 5.1.2</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>lodash < 4.17.21</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>path-parse < 1.0.7</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>ssri < 6.0.2</code> via <code>yarn.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=react-dart">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 353957eb2c929bc6ef86eca43f9f810b2f2e830f

Showing results for 353957eb2c929bc6ef86eca43f9f810b2f2e830f
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/react-dart/353957eb2c929bc6ef86eca43f9f810b2f2e830f).

**Review by joebingham-wk — APPROVED** [review]
+10

- [x] CI for both this and WSD passes! (with the exception of the beta line for this PR, which is failing on other PRs as well)

**Comment by sydneyjodon-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
