### PR TITLE
RM-95981 Release react-dart 6.1.0

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
Pulls included in this release:

- #316

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(5) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>browserslist < 4.16.5</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>elliptic < 6.5.4</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>glob-parent < 5.1.2</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>lodash < 4.17.21</code> via <code>yarn.lock</code></li>
<li>1 vulns in <code>ssri < 6.0.2</code> via <code>yarn.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=react-dart">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (6.0.1) as the diff base.</strong></em></p> Recommendation: **:warning: Minor version bump**


```diff
@@ line 112: package:react/src/react_client/factory_util.dart @@
+  JsMap generateJsProps(Map<dynamic, dynamic> props, {bool convertRefValue = true, bool convertCallbackRefValue = true, List<String> additionalRefPropKeys = const [], bool wrapWithJsify = true})
// Adding a top-level function is a minor change.
```

Showing results for 5a2e2d5708f72d4b23e4627c7d145c1c8a707b89
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/react-dart/5a2e2d5708f72d4b23e4627c7d145c1c8a707b89).

**Review by greglittlefield-wf — APPROVED** [review]
+10

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
